[tool.poetry]
name = "explingo"
version = "0.1.0dev1"
description = ""
authors = ["Ola Zytek <zyteka@mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dspy = "^0.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
